services:
  test_sweapi:
    build:
      dockerfile: ./test.Dockerfile
      # args:
      #   - GH_USER=${GH_USER}
      #   - GH_TOKEN=${GH_TOKEN}
    volumes:
      - ./:/test_sweisseph
    working_dir: /test_sweisseph
  sweapi:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "5678:5678"
