# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test with docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install build essentials
      run: sudo apt-get install -y build-essential

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.6'

    - name: Install Podman
      # You may pin to the exact commit or the version.
      # uses: gacts/install-podman@96e73075ee4b6669429c80458d063924472fb04d
      uses: gacts/install-podman@v1.1.1

    - name: Setup Podman Compose
      # You may pin to the exact commit or the version.
      # uses: webgtx/setup-podman-compose@33a94a0af6c428f0fd97fe5de9ee8718ed518423
      uses: webgtx/setup-podman-compose@v1

    - name: more setup`
      run: |
         sudo systemctl start podman.socket || true
         sudo systemctl is-active podman.service
         git reset --hard
         git clean -fd
          
    - name: Build project
      env:
        DOCKER_BUILDKIT: 0
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: make build-sweapi-test

    - name: Run Test
      env:
        DOCKER_BUILDKIT: 0
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: make sweapi-test
    
          
