# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test with docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install build essentials
      run: sudo apt-get install -y build-essential

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.6'

    - name: start docker
      run: sudo systemctl start docker

    - name: prepare build
      run: |
        git reset --hard
        git clean -fd
        docker build -f swe-builder.Dockerfile -t swe-builder:latest . 
        docker run --rm -v .:/workspace -w /workspace docker.io/bufbuild/buf generate proto
        docker compose -f compose.yaml build test_sweapi
        
    - name: Run Test
      run: docker compose -f compose.yaml run --rm test_sweapi
    
          
